### ISSUE TITLE
UnicodeDecoreError while running Pandas Profile with Streamlit

### ISSUE THREAD

**Issue by equester** [okld/streamlit-pandas-profiling#4]
Hi, 

I am getting following error:

2020-09-28 21:57:54.653 500 GET /component/streamlit_pandas_profiling.pandas_profiling/fonts/IBM_Plex_Sans/IBMPlexSans-Regular.ttf (::1) 7.00ms
variables: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 17.78it/s]
correlations [recoded]: 100%|█████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00,  6.98it/s]
interactions [continuous]: 100%|████████████████████████████████████████████████████████████████████████████████| 25/25 [00:05<00:00,  4.38it/s]
table: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.55it/s]
missing [dendrogram]: 100%|███████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  3.82it/s]
warnings [correlations]: 100%|███████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 751.04it/s]
package: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 99.69it/s]
build report structure: 100%|█████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.60s/it]
2020-09-29 10:01:11.706 Uncaught exception GET /component/streamlit_pandas_profiling.pandas_profiling/fonts/IBM_Plex_Sans/IBMPlexSans-Regular.ttf (::1)
HTTPServerRequest(protocol='http', host='localhost:8501', method='GET', uri='/component/streamlit_pandas_profiling.pandas_profiling/fonts/IBM_Plex_Sans/IBMPlexSans-Regular.ttf', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "C:\Users\lnigam\AppData\Roaming\Python\Python38\site-packages\tornado\web.py", line 1701, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "C:\Users\lnigam\AppData\Roaming\Python\Python38\site-packages\streamlit\components\v1\components.py", line 279, in get
    contents = file.read()
  File "c:\users\lnigam\appdata\local\continuum\anaconda3\envs\edureka_streamlit\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 210: character maps to <undefined>
2020-09-29 10:01:11.708 500 GET /component/streamlit_pandas_profiling.pandas_profiling/fonts/IBM_Plex_Sans/IBMPlexSans-Regular.ttf (::1) 4.00ms

Can you help me resolve this?

**Comment by Ghasel** [comment]
Hello @equester, could you provide some code to reproduce your issue? Thanks

**Comment by AVCarreiro** [comment]
I have the same error, which can be reproduced with:

```
df = pd.DataFrame(
    np.random.rand(100, 5),
    columns=['a', 'b', 'c', 'd', 'e']
)


st.write('## Details', df.sort_index())

pr = ProfileReport(df, explorative=True)

st.title("Pandas Profiling in Streamlit")
st_profile_report(pr)
```

Error:

Summarize dataset:  63%|████████████████████████████████████████████████████████████                                   | 12/19 [00:06<00:03,  1.94it/s, Get scatter matrix]
Summarize dataset: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 19/19 [00:07<00:00,  2.40it/s, Completed]
Generate report structure: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.18s/it]
Render HTML: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.04it/s]
2020-10-13 13:20:57.044 Uncaught exception GET /component/streamlit_pandas_profiling.pandas_profiling/fonts/IBM_Plex_Sans/IBMPlexSans-Regular.ttf (::1)
HTTPServerRequest(protocol='http', host='localhost:8501', method='GET', uri='/component/streamlit_pandas_profiling.pandas_profiling/fonts/IBM_Plex_Sans/IBMPlexSans-Regular.ttf', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "c:\users\andre.carreiro\anaconda3\envs\tf\lib\site-packages\tornado\web.py", line 1701, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "c:\users\andre.carreiro\anaconda3\envs\tf\lib\site-packages\streamlit\components\v1\components.py", line 292, in get
    contents = file.read()
  File "c:\users\andre.carreiro\anaconda3\envs\tf\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 210: character maps to <undefined>


Version: streamlit 0.68.1

**Comment by Ghasel** [comment]
Hello @AVCarreiro, thanks for the reply. I'll investigate the issue this week-end.

**Comment by okld** [comment]
@AVCarreiro and @equester, I've updated the component's dependencies, which seems to have solved the issue. You can do a `pip install --upgrade streamlit-pandas-profiling`.
